-- 種子資料：對應規格 §2.1 的實體版面
-- 黑板：全週固定職務 2 項、每日輪替職務 3 項
-- 白板：早修 10 點位、午休 10 點位
--
-- 容量上限：每人每個時段只能站一個點，所以單一時段的名額總數
-- 不能超過可排班的師傅數。目前 22 位師傅扣掉 2 位預備隊 = 20，
-- 因此暫定 10 點位 × 2 人 = 20 個名額，零餘裕。
-- 實際點位名冊到位後請一併檢查這個上限。

INSERT INTO location_tasks (board_type, shift_type, item_name, required_capacity, sort_order) VALUES
  ('BLACKBOARD', 'ALL_WEEK', '交接', 1, 10),
  ('BLACKBOARD', 'ALL_WEEK', '值日生', 1, 20),
  ('BLACKBOARD', 'DAILY', '餐車', 1, 30),
  ('BLACKBOARD', 'DAILY', '早修升旗', 1, 40),
  ('BLACKBOARD', 'DAILY', '午休回來', 1, 50),
  ('WHITEBOARD', 'MORNING', '育英樓', 2, 10),
  ('WHITEBOARD', 'MORNING', '教大', 2, 20),
  ('WHITEBOARD', 'MORNING', '7-11', 2, 30),
  ('WHITEBOARD', 'MORNING', '正門', 2, 40),
  ('WHITEBOARD', 'MORNING', '後門', 2, 50),
  ('WHITEBOARD', 'MORNING', '活動中心', 2, 60),
  ('WHITEBOARD', 'MORNING', '圖書館', 2, 70),
  ('WHITEBOARD', 'MORNING', '體育館', 2, 80),
  ('WHITEBOARD', 'MORNING', '川堂', 2, 90),
  ('WHITEBOARD', 'MORNING', '側門', 2, 100),
  ('WHITEBOARD', 'NOON', '育英樓', 2, 10),
  ('WHITEBOARD', 'NOON', '教大', 2, 20),
  ('WHITEBOARD', 'NOON', '7-11', 2, 30),
  ('WHITEBOARD', 'NOON', '正門', 2, 40),
  ('WHITEBOARD', 'NOON', '後門', 2, 50),
  ('WHITEBOARD', 'NOON', '活動中心', 2, 60),
  ('WHITEBOARD', 'NOON', '圖書館', 2, 70),
  ('WHITEBOARD', 'NOON', '體育館', 2, 80),
  ('WHITEBOARD', 'NOON', '川堂', 2, 90),
  ('WHITEBOARD', 'NOON', '側門', 2, 100);

-- 實際名冊：高一組 47 人（徒弟）、高二組 22 人（師傅），合計 69 人
-- 徒弟不排班；主管手動升級為師傅後才會進入排班池。
INSERT INTO staff (name, staff_group, role, sort_order) VALUES
  ('陳泓霖', '高一組', 'APPRENTICE', 1),
  ('莊沛璇', '高一組', 'APPRENTICE', 2),
  ('卓裕軒', '高一組', 'APPRENTICE', 3),
  ('黃宥璇', '高一組', 'APPRENTICE', 4),
  ('江楊若彤', '高一組', 'APPRENTICE', 5),
  ('施沛彤', '高一組', 'APPRENTICE', 6),
  ('楊濬萁', '高一組', 'APPRENTICE', 7),
  ('朱月', '高一組', 'APPRENTICE', 8),
  ('陳弘哲', '高一組', 'APPRENTICE', 9),
  ('趙彥瑾', '高一組', 'APPRENTICE', 10),
  ('謝承諺', '高一組', 'APPRENTICE', 11),
  ('邱子晉', '高一組', 'APPRENTICE', 12),
  ('顏佑倫', '高一組', 'APPRENTICE', 13),
  ('何冠勝', '高一組', 'APPRENTICE', 14),
  ('曾予咸', '高一組', 'APPRENTICE', 15),
  ('連宇翔', '高一組', 'APPRENTICE', 16),
  ('陳思璇', '高一組', 'APPRENTICE', 17),
  ('饒庭碩', '高一組', 'APPRENTICE', 18),
  ('謝丞皓', '高一組', 'APPRENTICE', 19),
  ('陳宇弘', '高一組', 'APPRENTICE', 20),
  ('周琖洋', '高一組', 'APPRENTICE', 21),
  ('邱則楷', '高一組', 'APPRENTICE', 22),
  ('吳沛潔', '高一組', 'APPRENTICE', 23),
  ('胡紫甯', '高一組', 'APPRENTICE', 24),
  ('陳則安', '高一組', 'APPRENTICE', 25),
  ('徐亦華', '高一組', 'APPRENTICE', 26),
  ('吳家捷', '高一組', 'APPRENTICE', 27),
  ('謝筱彤', '高一組', 'APPRENTICE', 28),
  ('吳沛戎', '高一組', 'APPRENTICE', 29),
  ('陳姿羽', '高一組', 'APPRENTICE', 30),
  ('温俐綺', '高一組', 'APPRENTICE', 31),
  ('劉宸鈞', '高一組', 'APPRENTICE', 32),
  ('張瑀恩', '高一組', 'APPRENTICE', 33),
  ('陳品芸', '高一組', 'APPRENTICE', 34),
  ('來恩萸', '高一組', 'APPRENTICE', 35),
  ('童珈靜', '高一組', 'APPRENTICE', 36),
  ('游智安', '高一組', 'APPRENTICE', 37),
  ('古采靜', '高一組', 'APPRENTICE', 38),
  ('游竣翔', '高一組', 'APPRENTICE', 39),
  ('邱念恩', '高一組', 'APPRENTICE', 40),
  ('詹妤靖', '高一組', 'APPRENTICE', 41),
  ('卓孟妍', '高一組', 'APPRENTICE', 42),
  ('陳崇証', '高一組', 'APPRENTICE', 43),
  ('葉倉豪', '高一組', 'APPRENTICE', 44),
  ('李宥萱', '高一組', 'APPRENTICE', 45),
  ('姚恩芯', '高一組', 'APPRENTICE', 46),
  ('徐侑暄', '高一組', 'APPRENTICE', 47),
  ('謝可薇', '高二組', 'MASTER', 101),
  ('羅于婷', '高二組', 'MASTER', 102),
  ('黃郁璇', '高二組', 'MASTER', 103),
  ('劉羽庭', '高二組', 'MASTER', 104),
  ('朱品瑜', '高二組', 'MASTER', 105),
  ('劉少庭', '高二組', 'MASTER', 106),
  ('邱怡茹', '高二組', 'MASTER', 107),
  ('陳意涵', '高二組', 'MASTER', 108),
  ('吳翰橙', '高二組', 'MASTER', 109),
  ('鄒恩浚', '高二組', 'MASTER', 110),
  ('林億玟', '高二組', 'MASTER', 111),
  ('林鈺真', '高二組', 'MASTER', 112),
  ('詹心萍', '高二組', 'MASTER', 113),
  ('何承煜', '高二組', 'MASTER', 114),
  ('劉彥甯', '高二組', 'MASTER', 115),
  ('曾楷婷', '高二組', 'MASTER', 116),
  ('林延霆', '高二組', 'MASTER', 117),
  ('張盛凱', '高二組', 'MASTER', 118),
  ('王柏勳', '高二組', 'MASTER', 119),
  ('林楷諺', '高二組', 'MASTER', 120),
  ('高以璇', '高二組', 'MASTER', 121),
  ('陳筠溱', '高二組', 'MASTER', 122);

INSERT INTO fairness_stats (staff_id, blackboard_count, morning_whiteboard_count, noon_whiteboard_count)
  SELECT staff_id, 0, 0, 0 FROM staff;
