-- 種子資料：點位取自主管提供的班表範本（白板／黑板表格）
--
-- 白板分三個時段：早修 → 升旗 → 午休，升旗底下再分定點與巡查。
-- 定點與巡查屬同一時段、共用名額上限：一個人在升旗時段只會站一個位置。
--
-- 範本每個點位只有一格「人員」，所以每點 1 人。
-- 單一時段的尖峰是升旗 19 個名額，22 位師傅足夠，
-- 每人每週約 10 次任務，不會有人整週閒著。

INSERT INTO location_tasks (board_type, shift_type, item_name, required_capacity, zone, sort_order) VALUES
  ('BLACKBOARD', 'ALL_WEEK', '交接', 1, '', 10),
  ('BLACKBOARD', 'ALL_WEEK', '值日生', 1, '', 20),
  ('BLACKBOARD', 'DAILY', '餐車', 1, '', 40),
  ('BLACKBOARD', 'DAILY', '早修', 1, '', 50),
  ('BLACKBOARD', 'DAILY', '午休', 1, '', 60),
  ('BLACKBOARD', 'DAILY', '校表', 1, '', 70),
  ('WHITEBOARD', 'MORNING', '廣興樓', 1, '', 10),
  ('WHITEBOARD', 'MORNING', '教大3-4F', 1, '', 20),
  ('WHITEBOARD', 'MORNING', '教大5-6F', 1, '', 30),
  ('WHITEBOARD', 'MORNING', '莊敬樓', 1, '', 40),
  ('WHITEBOARD', 'MORNING', '育英樓', 1, '', 50),
  ('WHITEBOARD', 'MORNING', '教大7-8F', 1, '', 60),
  ('WHITEBOARD', 'MORNING', '7-11', 1, '', 70),
  ('WHITEBOARD', 'MORNING', '更生樓', 1, '', 80),
  ('WHITEBOARD', 'MORNING', '自強+紀念', 1, '', 90),
  ('WHITEBOARD', 'MORNING', '教大電梯', 1, '', 100),
  ('WHITEBOARD', 'FLAG', '育英1F(中)', 1, '定點', 10),
  ('WHITEBOARD', 'FLAG', '7-11', 1, '定點', 20),
  ('WHITEBOARD', 'FLAG', '熱水台', 1, '定點', 30),
  ('WHITEBOARD', 'FLAG', '紀念館1F', 1, '定點', 40),
  ('WHITEBOARD', 'FLAG', '更生樓1F', 1, '定點', 50),
  ('WHITEBOARD', 'FLAG', '教務處走廊', 1, '定點', 60),
  ('WHITEBOARD', 'FLAG', '教大電梯', 1, '定點', 70),
  ('WHITEBOARD', 'FLAG', '廣興樓1F', 1, '定點', 80),
  ('WHITEBOARD', 'FLAG', '保健室1F', 1, '定點', 90),
  ('WHITEBOARD', 'FLAG', '廣興樓(右)2F', 1, '定點', 100),
  ('WHITEBOARD', 'FLAG', '育英2F(中)', 1, '定點', 110),
  ('WHITEBOARD', 'FLAG', '辦公室', 1, '巡查', 120),
  ('WHITEBOARD', 'FLAG', '教大345F', 1, '巡查', 130),
  ('WHITEBOARD', 'FLAG', '教大678F', 1, '巡查', 140),
  ('WHITEBOARD', 'FLAG', '育英樓', 1, '巡查', 150),
  ('WHITEBOARD', 'FLAG', '廣興樓', 1, '巡查', 160),
  ('WHITEBOARD', 'FLAG', '更生+莊敬', 1, '巡查', 170),
  ('WHITEBOARD', 'FLAG', '自強+紀念', 1, '巡查', 180),
  ('WHITEBOARD', 'FLAG', '地下室', 1, '巡查', 190),
  ('WHITEBOARD', 'NOON', '教大電梯+1-2F', 1, '', 10),
  ('WHITEBOARD', 'NOON', '教大3-4F', 1, '', 20),
  ('WHITEBOARD', 'NOON', '教大5-6F+空中花園', 1, '', 30),
  ('WHITEBOARD', 'NOON', '教大7-8F', 1, '', 40),
  ('WHITEBOARD', 'NOON', '紀念館1-6F', 1, '', 50),
  ('WHITEBOARD', 'NOON', '自強樓', 1, '', 60),
  ('WHITEBOARD', 'NOON', 'PU跑道', 1, '', 70),
  ('WHITEBOARD', 'NOON', '莊敬樓', 1, '', 80),
  ('WHITEBOARD', 'NOON', '更生樓', 1, '', 90),
  ('WHITEBOARD', 'NOON', '育英樓', 1, '', 100),
  ('WHITEBOARD', 'NOON', '廣興樓', 1, '', 110),
  ('WHITEBOARD', 'NOON', '711', 1, '', 120);

-- 實際名冊：高一組 47 人（徒弟）、高二組 22 人（師傅），合計 69 人
-- 徒弟不排班；主管手動升級為師傅後才會進入排班池。
INSERT INTO staff (name, staff_group, role, sort_order) VALUES
  ('陳泓霖', '高一組', 'APPRENTICE', 1),
  ('莊沛璇', '高一組', 'APPRENTICE', 2),
  ('卓裕軒', '高一組', 'APPRENTICE', 3),
  ('黃宥璇', '高一組', 'APPRENTICE', 4),
  ('江楊若彤', '高一組', 'APPRENTICE', 5),
  ('施沛彤', '高一組', 'APPRENTICE', 6),
  ('楊濬萁', '高一組', 'APPRENTICE', 7),
  ('朱月', '高一組', 'APPRENTICE', 8),
  ('陳弘哲', '高一組', 'APPRENTICE', 9),
  ('趙彥瑾', '高一組', 'APPRENTICE', 10),
  ('謝承諺', '高一組', 'APPRENTICE', 11),
  ('邱子晉', '高一組', 'APPRENTICE', 12),
  ('顏佑倫', '高一組', 'APPRENTICE', 13),
  ('何冠勝', '高一組', 'APPRENTICE', 14),
  ('曾予咸', '高一組', 'APPRENTICE', 15),
  ('連宇翔', '高一組', 'APPRENTICE', 16),
  ('陳思璇', '高一組', 'APPRENTICE', 17),
  ('饒庭碩', '高一組', 'APPRENTICE', 18),
  ('謝丞皓', '高一組', 'APPRENTICE', 19),
  ('陳宇弘', '高一組', 'APPRENTICE', 20),
  ('周琖洋', '高一組', 'APPRENTICE', 21),
  ('邱則楷', '高一組', 'APPRENTICE', 22),
  ('吳沛潔', '高一組', 'APPRENTICE', 23),
  ('胡紫甯', '高一組', 'APPRENTICE', 24),
  ('陳則安', '高一組', 'APPRENTICE', 25),
  ('徐亦華', '高一組', 'APPRENTICE', 26),
  ('吳家捷', '高一組', 'APPRENTICE', 27),
  ('謝筱彤', '高一組', 'APPRENTICE', 28),
  ('吳沛戎', '高一組', 'APPRENTICE', 29),
  ('陳姿羽', '高一組', 'APPRENTICE', 30),
  ('温俐綺', '高一組', 'APPRENTICE', 31),
  ('劉宸鈞', '高一組', 'APPRENTICE', 32),
  ('張瑀恩', '高一組', 'APPRENTICE', 33),
  ('陳品芸', '高一組', 'APPRENTICE', 34),
  ('來恩萸', '高一組', 'APPRENTICE', 35),
  ('童珈靜', '高一組', 'APPRENTICE', 36),
  ('游智安', '高一組', 'APPRENTICE', 37),
  ('古采靜', '高一組', 'APPRENTICE', 38),
  ('游竣翔', '高一組', 'APPRENTICE', 39),
  ('邱念恩', '高一組', 'APPRENTICE', 40),
  ('詹妤靖', '高一組', 'APPRENTICE', 41),
  ('卓孟妍', '高一組', 'APPRENTICE', 42),
  ('陳崇証', '高一組', 'APPRENTICE', 43),
  ('葉倉豪', '高一組', 'APPRENTICE', 44),
  ('李宥萱', '高一組', 'APPRENTICE', 45),
  ('姚恩芯', '高一組', 'APPRENTICE', 46),
  ('徐侑暄', '高一組', 'APPRENTICE', 47),
  ('謝可薇', '高二組', 'MASTER', 101),
  ('羅于婷', '高二組', 'MASTER', 102),
  ('黃郁璇', '高二組', 'MASTER', 103),
  ('劉羽庭', '高二組', 'MASTER', 104),
  ('朱品瑜', '高二組', 'MASTER', 105),
  ('劉少庭', '高二組', 'MASTER', 106),
  ('邱怡茹', '高二組', 'MASTER', 107),
  ('陳意涵', '高二組', 'MASTER', 108),
  ('吳翰橙', '高二組', 'MASTER', 109),
  ('鄒恩浚', '高二組', 'MASTER', 110),
  ('林億玟', '高二組', 'MASTER', 111),
  ('林鈺真', '高二組', 'MASTER', 112),
  ('詹心萍', '高二組', 'MASTER', 113),
  ('何承煜', '高二組', 'MASTER', 114),
  ('劉彥甯', '高二組', 'MASTER', 115),
  ('曾楷婷', '高二組', 'MASTER', 116),
  ('林延霆', '高二組', 'MASTER', 117),
  ('張盛凱', '高二組', 'MASTER', 118),
  ('王柏勳', '高二組', 'MASTER', 119),
  ('林楷諺', '高二組', 'MASTER', 120),
  ('高以璇', '高二組', 'MASTER', 121),
  ('陳筠溱', '高二組', 'MASTER', 122);

INSERT INTO fairness_stats (staff_id, blackboard_count, morning_whiteboard_count, noon_whiteboard_count)
  SELECT staff_id, 0, 0, 0 FROM staff;
